baseURL = 'https://j1king.github.io/'
languageCode = 'ko-kr'
title = "j1king"
theme = 'PaperMod'

[pagination]
  pagerSize = 10

[params]
  defaultTheme = "dark"
  disableThemeToggle = false
  disableSpecial1stPost = true
  showReadingTime = true
  showPostNavLinks = true
  showCodeCopyButtons = true
  hideSummary = false
  showtoc = true

[params.profileMode]
  enabled = false

[markup.goldmark.renderer]
  unsafe = true

[markup.highlight]
  style = "dracula"
